<<<<<<< HEAD
name: "PhaNDoMs Security Blog"
author: PhaNDoMs
baseurl: /
description: My WriteUps and other blogposts
github: http://www.github.com/PhaNDoMs
twitter: http://www.twitter.com/PhaNDoMs_EU
#facebook: http://www.facebook.comdomi.schlegel
linkedin: http://www.linkedin.com
email: rnpatel[at]me.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
